Initial release
Codeception/module-phalcon5 pull request #1
Opened 2021-12-12 13:31 UTC by niden

Code for 1.0.0 release.

- Changed all references from `phalcon4` to `phalcon5`
- Made necessary changes to namespaces for `Di` and `Url` since those classes were moved to new locations

Tests are failing because the CI expects phalcon-5.0.0beta1. Once this is released, we can release beta1 and then the tests will pass.

2021-12-12 13:31 UTC, niden commented
@DavertMik When you get a chance please have a look at this.

2021-12-13 09:32 UTC, Jeckerson requested changes

2021-12-13 09:32 UTC, Jeckerson commented on tests/unit/Phalcon4ModuleTest.php
> +<?php
Name of the file is incorrect

2021-12-13 09:32 UTC, Jeckerson commented on tests/unit/Phalcon4ConnectorTest.php
> +<?php
Name of the file is incorrect

2021-12-13 13:00 UTC, niden commented on tests/unit/Phalcon4ConnectorTest.php
> +<?php
Corrected

2021-12-13 13:00 UTC, niden commented on tests/unit/Phalcon4ModuleTest.php
> +<?php
Corrected

2021-12-13 16:45 UTC, Jeckerson approved these changes

2021-12-13 16:45 UTC, merged